// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njprdfdqsyotefgnpaxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcHJkZmRxc3lvdGVmZ25wYXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDE0NDUsImV4cCI6MjA2MDAxNzQ0NX0.-12UY93MHXJGaRVe1Qs3kLUehj60A_ulHkeoO3pO7xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});